// Translate at the presentation boundary; encounter rules and saved scores stay language-neutral.
let language = 'en';
export function setEnvyLanguage(value) { language = value?.startsWith('zh') ? 'zh-Hant' : 'en'; return language; }
export function envyLanguage() { return language; }
const pairs = [
  ['空白鍵','Space'],['眼球','Eyes'],['特','Special'],
  ['完整挑戰','Full challenge'],['窺視之子','The Watching Child'],['多眼龍','Many-Eyed Dragon'],['獨眼觸手','One-Eyed Tendrils'],['狂暴巨瞳','Enraged Great Eye'],
  ['逃離後 · Bridge 反攻','Final Bridge counterattack'],['捕捉綠色本體 · 隨機迷宮','Catch the true body · Random maze'],['卡牌演出 · 固定示範','Card reveal · Demo'],['限時 60 秒','60-second challenge'],
  ['嫉妒本體','True Envy'],['嫉妒化身','Envy Incarnate'],['反攻成功','Counterattack!'],['塔羅護佑','Tarot shield'],['嫉妒暴走 · 反攻機會','Enraged · Counterattack chance'],
  ['下次攻擊減半','Next attack damage halved'],['秘藏令嫉妒暴走','Treasure enrages Envy'],['移速被偷走','Speed stolen'],['逃出視線 · 消行擊破巨瞳','Escaped · Clear lines to finish Envy'],['巨瞳仍在窺視 · 重新蓄力','Still watching · Preparing again'],
  ['左右反轉','Reversed'],['黑幕','Blind'],['急落','Fast fall'],['禁止旋轉','No rotation'],['封印保留','Hold locked'],['垃圾上升','Garbage rise'],['懲罰','Penalty'],['獎勵 · 開啟嫉妒挑戰','Reward · Envy challenge'],['獎勵 · 回復','Reward · Heal'],['貓送來魚乾','The cat brought a treat'],
  ['偷窺之窗','Peeping Windows'],['眼睛收藏室','Eye Collection Room'],['窺視之橋','Watching Bridge'],['尋找異瞳','Spot the Odd Eye'],['命運塔羅','Tarot of Fate'],['滾石入瞳','Rolling Stone'],['嫉妒秘藏','Envy Treasures'],['眼界爭奪','Claim the Territory'],['幽林巡遊','Forest Patrol'],['六眼鐳射','Six-Eye Lasers'],['偷竊','Theft'],['嫉妒凝視','Envious Gaze'],['萬眼天羅','Eye Net'],['嫉妒龍息','Envious Dragon Breath'],['瞳孔迷宮','Pupil Maze'],['六眼交織','Crossing Eye Lasers'],['竊命之觸','Life-Stealing Touch'],['三重凝視','Triple Gaze'],['逃離巨瞳','Escape the Great Eye'],['捕捉嫉妒本體','Catch True Envy'],
  ['拖曳擦窗・方向鍵移動＋長按空白鍵','Drag to erase · Arrows + hold Space'],['左右轉房・上下選物・空白鍵查看・C 返回','←→ Room · ↑↓ Select · Space Inspect · C Back'],['方向鍵移動・空白鍵下落・C 保留','Arrows Move · Space Drop · C Hold'],['找出不同的眼球，完成三輪','Pick the odd eye · Complete 3 rounds'],['空白鍵翻牌，再按一次收下命運','Space Reveal · Press again to accept'],['方向鍵滾動，直立落入眼球洞','Arrows Roll · Enter the hole upright'],['空白鍵拆包／翻牌，收下三張秘藏','Space Reveal / Accept · Collect 3 cards'],['圈回綠地佔領領域，避開尾巴上的眼鬼','Return to green to claim land · Guard your trail'],['收集光點・綠果反制三隻追蹤眼鬼','Collect lights · Green fruit counters ghosts'],['預告線亮起時，移出射線','Dodge the beam when warning lines appear'],['避開抓取線；被抓按空白鍵斷繩取回血','Dodge claws · If caught, tap Space to break free'],['不停移動，離開追蹤視線','Keep moving · Dodge the tracking gaze'],['走綠色缺口；靠近金眼按空白鍵擊碎','Use green gaps · Space near gold eyes to break'],['引龍息燒小眼，燒滿五隻可反攻','Lure fire into 5 small eyes to counterattack'],['走到沒有眼紋的盲點，停留三秒','Find the unmarked blind spot · Stay 3 seconds'],['六眼交叉發射，留意下一組預告','Crossing lasers · Watch the next warning'],['躲雙觸手；被抓按空白鍵搶回血','Dodge both claws · Tap Space to reclaim HP'],['離開輪流追蹤的三道視線','Dodge the three alternating tracking gazes'],['← 停在樹後避光・→ 跑・空白鍵跳','← Hide behind trees · → Run · Space Jump'],['沿腳印追蟲・C 衝刺・靠近按空白鍵','Follow tracks · C Dash · Space nearby to catch'],
  ['月亮','Moon'],['寶劍','Sword'],['小丑','Jester'],['眼睛','Eye'],['死神','Death'],['逆位','Reversed'],['正位','Upright'],['晨光護符','Dawn Charm'],['冰晶靈藥','Frost Elixir'],['赤瞳龍面','Crimson Dragon Mask'],['翡翠秘典','Emerald Codex'],['萬眼龍 · 秘藏','Many-Eyed Dragon · Treasure'],['命運之書','Book of Fate'],['空白鍵 · 揭開秘藏','Space · Reveal treasure'],
  ['下次攻擊受傷減半','Next attack: damage taken halved'],['下次攻擊：受傷 +50%','Next attack: damage taken +50%'],['同回合：反攻 +30%','Same round: counterattack +30%'],['反攻 Boss','Boss damage'],['自己扣','Lose'],
  ['受到窺視攻擊','Hit by the watching eyes'],['突破窺視！','Gaze broken!'],['挑戰未完成','Challenge failed'],['找到異瞳！','Odd eye found!'],['再看清楚瞳孔','Look closely at the pupil'],['秘藏現身','Treasure revealed'],['跌落 · 回到起點','Fell · Back to the start'],['直立入洞！','Upright into the hole!'],['圈回領域！','Territory claimed!'],['綠果 · 反制眼鬼','Green fruit · Counter the ghosts'],['追蹤衝刺！','Tracking dash!'],['捉到嫉妒本體！','True Envy caught!'],['搶回生命！','Life reclaimed!'],['反擊觸手！','Tendril countered!'],['擊碎金眼！','Gold eye broken!'],['反制眼鬼！','Ghost countered!'],['被抓！連按空白鍵斷繩','Caught! Tap Space to break free'],['引火燒瞳！','Eye burned!'],['拾到幽林綠果','Forest fruit collected'],['離開照射線，或停在樹後','Dodge the light or hide behind a tree'],['本體逃到更深處，可重試','It escaped deeper · Try again'],
  ['新玩具','New toys'],['被稱讚','Being praised'],['開心家庭','Happy family'],['收到禮物','Getting gifts'],['得到掌聲','Applause'],['有人陪伴','Companionship'],['床邊','Bedside'],['書桌','Desk'],['畫牆','Picture wall'],['面具','Mask'],['枕頭','Pillow'],['床底','Under bed'],['盒子','Box'],['抽屜','Drawer'],['密碼盒','Code box'],['倒置畫','Upside-down picture'],['窗簾','Curtain'],['便條','Note'],['已找到','Found'],['轉房','Room'],['鑰匙','Key'],
  ['抽屜便條','Drawer note'],['面具眼洞 · 由左至右','Mask sockets · Left to right'],['點一下返回','Tap to go back'],['上半加 · 下半減','Top + · Bottom −'],['空白鍵 · 開盒','Space · Open box'],['星星要朝上','Turn the star upright'],['點畫／空白鍵 · 轉動','Tap picture / Space · Rotate'],['眼洞對上偷來的人生','Match each socket to a stolen life'],['空白鍵 · 放入眼球','Space · Place eye'],['六段人生，沒有一段屬於我','Six lives. None of them are mine.'],['主眼的秘密 · 劇情試作','The main eye’s secret · Story preview'],
  ['鑰匙拼好了，去開抽屜','Key complete · Open the drawer'],['找到半截鑰匙','Half a key found'],['缺少另一半鑰匙','Find the other half of the key'],['便條上的三個數字','Use the three numbers on the note'],['讓畫中的星星朝上','Turn the picture’s star upright'],['記住數字與眼洞順序','Remember the code and socket order'],['先找齊五隻眼；最後一隻藏在面具','Find 5 eyes first · The last is in the mask'],['密碼不符，回看便條','Wrong code · Check the note'],['再轉一次','Rotate again'],['眼紋不符，看看便條','Wrong pattern · Check the note'],['還未找到這種眼球','You have not found this eye yet'],['先放好五隻眼，最後眼洞才會開','Place 5 eyes to open the last socket'],['眼洞亮了','Socket lit'],
  ['封印','Locked'],['下一個','Next'],['留','Hold'],['移速減慢','Slowed'],['滾動中','Rolling'],['橫躺 · 佔兩格','Lying flat · 2 tiles'],['直立 · 佔一格','Upright · 1 tile'],['空白鍵 捕捉！','Space · Catch!'],['衝刺中','Dashing'],['C 衝刺可用','C · Dash ready'],['空白鍵斷繩','Space · Break free'],['金眼','Gold eyes'],['引燃','Burned'],['快跑','Run!'],['樹後 · 視線擋住了','Behind tree · Hidden'],['即將照射 · 躲樹後','Light incoming · Hide behind a tree'],['照射中 · 離開亮區','Light active · Leave the lit area'],['樹','Tree'],
  ['主眼的秘密','The Main Eye’s Secret'],['巨瞳睜眼','The Great Eye Opens'],['窺視之子倒下了','The Watching Child Falls'],['擊破嫉妒化身','Envy Incarnate Defeated'],['原來，這才是本體','The True Body Revealed'],['擊破嫉妒 · 捕獲本體','Envy Defeated · True Body Caught'],['嫉妒已敗 · 本體逃入幽林','Envy Defeated · True Body Escaped'],['被嫉妒吞沒','Consumed by Envy'],['挑戰完成','Challenge complete'],['本體溜走了','The True Body Escaped'],
  ['眼球深處，有東西正在甦醒。','Something stirs deep within the eye.'],['眾目熄滅，只剩逃跑的身影。','The eyes go dark. A small figure flees.'],['眾目熄滅，只剩一個逃跑的身影。','The eyes go dark. A small figure flees.'],['追進幽林，抓住它。','Follow it into the forest. Catch it.'],['擊破化身，捕獲嫉妒本體。','The incarnation is defeated. True Envy is caught.'],['巨瞳散去，本體逃入幽林。','The great eye fades. Its true body flees.'],['換個節奏，再試一次。','Find your rhythm. Try again.'],['本體仍藏在幽林深處。','Its true body still hides deep in the forest.'],['巨瞳散去，森林再次沉睡。','The great eye fades. The forest sleeps again.'],['那些眼睛，總在看著別人。','Those eyes always watch other people.'],['逃離它的視線。','Escape its gaze.'],['嫉妒，長出了新的眼睛。','Envy has grown new eyes.'],['最後反攻 · 消行擊破巨瞳','Final counterattack · Clear lines to finish Envy'],['揭示中','Revealing'],['空白鍵 · 確認收牌','Space · Accept card'],['看見幸福 · 空白鍵下一窗','Happiness revealed · Space Next window'],
  ['巨瞳鎖血','Boss HP locked'],['暴走 · 反攻強化','Enraged · Stronger counterattacks'],['盲點封印','Seal blind spot'],['找到盲點','Find the blind spot'],['捕捉本體','Catch true body'],['領域','Territory'],['光點','Lights'],['終點','Progress'],['架塊','Bridge'],['窗 · 擦開','windows · Erased'],[' 輪',' rounds'],[' 關',' stages'],[' 張',' cards'],[' 秒','s'],['回復','Heal'],['受到傷害','Damage'],['移動','Moves'],['撤回','Undo'],[' 次跌落',' falls'],['衝刺','Dash'],['斷繩','Break free'],
  ['嫉妒挑戰','Envy Challenge'],['嫉妒試玩','Envy Preview'],['幽林裡的眼睛，正在窺視你。','Eyes in the dark forest are watching you.'],['挑戰內容','Challenge'],['試玩內容','Scenario'],['難度','Difficulty'],['開始挑戰','Start challenge'],['開始試玩','Start preview'],['☰ 可重試／返回關卡。已接入七首嫉妒專屬音樂。','☰ Retry or return to stages. Seven Envy tracks included.'],['☰ 可重試／換關。已接入七首嫉妒專屬音樂。','☰ Retry or choose a scenario. Seven Envy tracks included.'],
  ['遊戲已暫停','Game paused'],['試玩已暫停','Preview paused'],['方向鍵：移動／選擇','Arrows: move / select'],['空白鍵：主要動作','Space: main action'],['C：保留／撤回／衝刺／返回','C: hold / undo / dash / back'],['繼續遊玩','Resume'],['重新挑戰','Restart challenge'],['重試這一關','Retry scenario'],['返回關卡','Stages'],['換一關','Choose scenario'],['換關','Scenarios'],['秘藏收藏','Treasure collection'],['略過捕蟲 · 結算','Skip capture · Finish'],['危險效果','Danger effect'],['紅色 Warning · 不抖動','Red warning · No shake'],['抖動','Shake'],['減少動態效果','Reduce motion'],['音樂音量','Music volume'],['音樂','Music'],['音效','Sound effects'],['返回遊戲','Back to game'],['只保留本次挑戰取得的卡片。','Cards collected in this challenge only.'],['只保留本次試玩取得的卡片。','Cards collected in this preview only.'],['還沒有秘藏，試試多眼龍的卡包回合。','No treasures yet. Try the dragon’s card packs.'],
  ['繼續挑戰','Continue challenge'],['繼續','Continue'],['直接結算','Finish'],['重試','Retry'],['返回','Back'],['下一窗','Next'],['擦拭','Erase'],['開盒','Open'],['放入','Place'],['轉畫','Turn'],['查看','Inspect'],['選擇','Select'],['收牌','Accept'],['翻牌','Reveal'],['拆包','Open'],['捕捉','Catch'],['跳躍','Jump'],['打斷','Break'],['擊碎','Shatter'],['回一步','Undo'],['右旋','Turn'],['左旋','L turn'],['上移','Up'],['下移','Down'],['加數','+'],['減數','−'],['選眼','Eye'],['選物','Item'],['落','Drop'],['降','Down'],
  ['開啟遊戲選單','Open game menu'],['開啟試玩選單','Open preview menu'],['嫉妒遊戲框','Envy playfield'],['遊戲操作','Game controls'],['反向旋轉','Rotate counterclockwise'],['旋轉','Rotate'],['向左','Move left'],['向右','Move right'],['向上','Move up'],['緩降','Soft drop'],['向下','Move down'],['原有貓咪','Original cat'],['貓咪','Cat'],['嫉妒','Envy'],
];
const dictionary = new Map(pairs);
const escaped = [...dictionary.keys()].sort((a,b)=>b.length-a.length).map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
const pattern = new RegExp(escaped.join('|'),'gu');
export function t(value) {
  if (value == null || language !== 'en') return value;
  let label = String(value);
  if (!/\p{Script=Han}/u.test(label)) return label;
  label = label.replace(/找到「(.+?)」之眼/g,(_,life)=>`Found the “${t(life)}” eye`).replace(/看見「(.+?)」/g,(_,life)=>`Saw “${t(life)}”`);
  return label.replace(pattern,match=>dictionary.get(match));
}

// Remember only static HTML labels; dynamic encounter text is translated at render time.
export function captureInterface(root) {
  const labels = [];
  const visit = node => {
    if (node.nodeType === 3 && node.textContent.trim()) labels.push([node,null,node.textContent]);
    if (node.nodeType !== 1 && node !== root) return;
    if (node.matches?.('script,style,#envy-language')) return;
    for (const attribute of ['aria-label','alt']) if (node.hasAttribute?.(attribute)) labels.push([node,attribute,node.getAttribute(attribute)]);
    for (const child of node.childNodes) visit(child);
  };
  visit(root);
  return () => { for (const [node,attribute,source] of labels) attribute ? node.setAttribute(attribute,t(source)) : node.textContent = t(source); };
}
